// <auto-generated />
using System;
using CoursesDBProject.Tables;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoursesDBProject.Migrations
{
    [DbContext(typeof(InfoSupportDbContext))]
    [Migration("20230320135109_CourseInstances")]
    partial class CourseInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("CoursesDBProject.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("duur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CoursesTable");
                });

            modelBuilder.Entity("CoursesDBProject.Entities.CourseInstance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("courseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("startdatum")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("courseId");

                    b.ToTable("CourseInstance");
                });

            modelBuilder.Entity("CoursesDBProject.Entities.CourseInstance", b =>
                {
                    b.HasOne("CoursesDBProject.Entities.Course", "course")
                        .WithMany("courses")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");
                });

            modelBuilder.Entity("CoursesDBProject.Entities.Course", b =>
                {
                    b.Navigation("courses");
                });
#pragma warning restore 612, 618
        }
    }
}
